# Generated by Django 4.2.7 on 2023-11-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Календарь",
                "verbose_name_plural": "Календари",
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Соревнование",
                "verbose_name_plural": "Соревнования",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=256, verbose_name="Фамилия"),
                ),
                ("surname", models.CharField(max_length=256, verbose_name="Отчество")),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                ("image", models.ImageField(null=True, upload_to="media/players/")),
                ("address", models.CharField(max_length=256)),
                ("identificator", models.CharField(max_length=12, verbose_name="ИИН")),
                ("email", models.EmailField(max_length=256)),
                ("phone_number", models.CharField(max_length=11)),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Стадия",
                "verbose_name_plural": "Стадий",
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "comp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Турнир",
                "verbose_name_plural": "Турниры",
            },
        ),
        migrations.CreateModel(
            name="StructureTournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.stage"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Структура Турнира",
                "verbose_name_plural": "Структура Турниров",
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.calendar"
                    ),
                ),
                ("player", models.ManyToManyField(to="main.player")),
            ],
            options={
                "verbose_name": "Состав на матч",
                "verbose_name_plural": "Составы на матчи",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("time", models.TimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.calendar"
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.stage"
                    ),
                ),
                ("teams_in", models.ManyToManyField(to="main.teams")),
            ],
            options={
                "verbose_name": "Матч",
                "verbose_name_plural": "Матчи",
            },
        ),
        migrations.CreateModel(
            name="Connect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.calendar"
                    ),
                ),
                ("teams", models.ManyToManyField(to="main.teams")),
            ],
            options={
                "verbose_name": "Привязка команды",
                "verbose_name_plural": "Привязка команд",
            },
        ),
        migrations.AddField(
            model_name="calendar",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.tournament"
            ),
        ),
    ]
